version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates every Monday
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitsubmodule"
    directory: "json"
    schedule:
      interval: "weekly"
